import React from "react";
import { Link } from "react-router-dom";

function Privacy() {
  return (
    <>
      <div className="container">
        <h2 style={{ textAlign: "center" }}>
          <b>PRIVACY POLICY</b>
        </h2>
        {/* <p>Effective date: 2023-11-30</p> */}
        <p>
          1. <b>Introduction</b>
        </p>
        <p>Our Privacy Policy was last updated on 27/01/2024.</p>
        <p>
          This Privacy Policy describes our policies and procedures on the
          collection, use and disclosure of your information when you use the
          Service and tells you about your privacy rights and how the law
          protects you.
        </p>
        <p>
          We use your Personal data to provide and improve the Service. By using
          the Service, you agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>
        <b>Interpretation and Definitions</b>
        <p>
          <b>1. Interpretation</b>
        </p>
        <p>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>

        <p>
          <b> 2.Definitions</b>
        </p>
        <p>For the purposes of this Privacy Policy:</p>
        <p>
          <b>ACCOUNT</b> means a unique account created for you to access our
          Service or parts of our Service to manage customer booking as an agent
          by filling their basic details.
        </p>
        <p>
          <b>APPLICATION</b> means the software program provided by the Company
          downloaded by you on any electronic device, named Sai Group.
        </p>
        <p>
          <b>COMPANY</b> (referred to as either &quot;the Company&quot;,
          &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement)
          refers to Sai Satish Group
        </p>
        <p>
          <b>Country</b> refers to India.
        </p>
        <p>
          <b>COOKIES</b> are small files that are placed on your computer,
          mobile device or any other device by a website, containing the details
          of your browsing history on that website among its many uses.
        </p>
        <p>
          <b>DEVICE</b> means any device that can access the Service such as a
          computer, a cell phone or a digital tablet.
        </p>
        <p>
          <b>PERSONAL DATA</b> is any information that relates to an identified
          or identifiable individual.
        </p>
        <p>
          <b>SERVICE</b> refers to the sai yatra booking through our app or Sai
          Yantra Sales.
        </p>
        <p>
          <b>SERVICE PROVIDER</b> means any natural or legal person who
          processes the data on behalf of the Company. It refers to third-party
          companies or individuals employed by the Company to facilitate the
          Service, to provide the Service on behalf of the Company, to perform
          services related to the Service or to assist the Company in analyzing
          how the Service is used.
        </p>
        <p>
          <b>USAGE DATA</b> refers to data collected automatically, either
          generated by the use of the Service or from the Service infrastructure
          itself .
        </p>
        <p>
          <b>YOU</b> means the individual accessing or using the Service, or the
          company, or other legal entity on behalf of which such individual is
          accessing or using the Service, as applicable.
        </p>
        <p>
          3. <b>Collecting and Using your Personal Data</b>
        </p>
        <p>
          <b>Types of Data Collected</b>
        </p>
        <b>Personal Data</b>
        <p>
          While using Our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you. Personally identifiable information may include, but is
          not limited to:
        </p>
        <p>0.1. Email address</p>
        <p>0.2. First name and last name </p>
        <p>0.3. Phone number</p>
        <p>0.4. Address, State, Province, ZIP/Postal code, City</p>

        <p>0.5.Usage Data</p>
        <p>
          Personal data listed above are sent to our system to manage your
          account and give you access to app functionalities of which are
          available to our registered users only.
        </p>

        <b>Usage Data</b>
        <p>Usage Data is collected automatically when using the Service.</p>
        <p>
          Usage Data may include information such as your Device&#39;s Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that you visit, the time and date of your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data.
        </p>
        <p>
          We may also collect information that your browser sends whenever you
          visit our Service or when you access the Service by or through a
          mobile device.
        </p>
        <p>
          <b>Information Collected while Using the Application:</b>
        </p>
        <p>
          The app does use third-party services that may collect information
          used to identify you. Link to the privacy policy of third-party
          service providers used by the app:
        </p>
        <p>
          <a
            href="https://policies.google.com/privacy"
            target="_blank"
            rel="noopener noreferrer"
          >
            <b>0.1. Google Play Services</b>
          </a>
        </p>

        <p>
          <a
            href="https://firebase.google.com/policies/analytics"
            target="_blank"
            rel="noopener noreferrer"
          >
            <b>0.2. Google Analytics for Firebase</b>
          </a>
        </p>
        <p>
          <a
            href="https://firebase.google.com/support/privacy"
            target="_blank"
            rel="noopener noreferrer"
          >
            <b>0.3. Firebase Crashlytics</b>
          </a>
        </p>

        <p>
          <b>Profile Display :</b>
        </p>
        <p>
          Your uploaded images may be displayed as part of your user profile
          within the app.
        </p>
        <p>
          <b>App Functionality :</b>
        </p>
        <p>
          Images may be used to enhance app functionality, such as recognizing
          and displaying user-generated content.
        </p>
        <p>
          <b>Third-Party Sharing :</b>
        </p>
        <p>
          We do not share your uploaded images with third parties without your
          explicit consent. However, it&#39;s important to note that if you
          choose to share your images through our app&#39;s features, they may
          become accessible to other users based on your sharing settings.
        </p>
        <p>
          <b>Consent :</b>
        </p>
        <p>
           By uploading images to our app, you provide explicit consent for us
          to collect, store, and use those images for the purposes outlined in
          this Privacy Policy. You can withdraw your consent at any time by
          deleting the images from your account or contacting our support team.
        </p>
        <p>
          <b>Retention and Deletion :</b>
        </p>
        <p>
           We retain your uploaded images for as long as necessary to fulfill
          the purposes for which they were collected and to comply with our
          legal obligations. If you choose to delete your images from our app,
          they will be removed from our active servers. However, please note
          that cached or backup copies of your images may persist for a limited
          period.
        </p>
        <p>
          <b>Security Measures :</b>
        </p>
        <p>
           We take the security of your images seriously and implement
          industry-standard measures to protect them from unauthorized access,
          loss, or misuse. These measures include encryption, access controls,
          and regular security assessments.
        </p>
        <p>
          <b>5. Use of your Personal Data</b>
        </p>
        <p>The Company may use Personal Data for the following purposes:</p>
        <p>
          0.1. <b>To provide and maintain our Service, </b>including to monitor
          the usage of our Service.
        </p>
        <p>
          0.2. <b>To manage your Account: </b>to manage your registration as a
          user of the Service. The Personal Data you provide can give you access
          to different functionalities of the Service that are available to you
          as a registered user.
        </p>
        <p>
          0.3. <b>For the performance of a contract:</b> the development,
          compliance and undertaking of the purchase contract for the products,
          items or services you have purchased or of any other contract with us
          through the Service.
        </p>

        <p>
          0.4. <b>To contact you: </b>To contact you by email, telephone calls,
          SMS, or other equivalent forms of electronic communication, such as a
          mobile application&#39;s push notifications regarding updates or
          informative communications related to the functionalities, products or
          contracted services, including the security updates, when necessary or
          reasonable for their implementation.
        </p>
        <p>
          0.5. <b>To manage your requests:</b> To attend and manage your
          requests to us.
        </p>
        <p>
          0.6. <b>For other purposes:</b> We may use your information for other
          purposes, such as data analysis, identifying usage trends, determining
          the effectiveness of our promotional campaigns and to evaluate and
          improve our Service, products, services, marketing and your
          experience.
        </p>
        <p>
          <b>6. Third Parties</b>
        </p>
        <p>
          Sometimes we ask outside firms, or third parties, to help us provide
          services, such as sending emails, registering a prospective domain
          name, or analyzing data. Our contracts with these third parties
          outline the appropriate use and handling of your information and
          prohibit them from using any of your personal information for purposes
          unrelated to the product or service they’re providing. We require
          vendors to maintain the confidentiality of the information we provide
          to them. We may disclose, access, or report personal information when
          we believe, in good faith, we’re required to by law or to protect our
          legal rights. We may also do this in connection with an investigation
          into a suspected violation involving the Terms of Service, fraud,
          intellectual property infringement, or other activity that may be
          illegal or expose us to legal liability. For example, we may be
          required to disclose personal information to cooperate with regulators
          or law enforcement authorities or to comply with a court order,
          subpoena, search warrant, or law enforcement request. We work with
          other companies or developers to provide you with products and
          services which we clearly identify. company may offer these products
          and services. We clearly identify these co-branded products and
          services. In some cases, we exchange customer usage information to
          establish and provide ongoing service. By requesting these products or
          services, users are permitting us to provide their personal and usage
          information to the other company.
        </p>
        <p>
          We also may share non-identifiable, non-personal aggregate information
          about our users with third parties, such as advertisers or partners,
          for marketing and promotional purposes. Our Websites may provide links
          to third-party sites, such as those of our business partners and
          online advertisers. These could include other services, promotions or
          sweepstakes offered by business partners. Because our app does not
          control the information policies or practices of these third parties,
          you should review their privacy policies to learn more about how they
          collect and use personal information. If we sell, merge or transfer
          any part of our business, part of the sale may include your personal
          information. If so, you will be asked if you’d like to stop receiving
          promotional information following any change of control.
        </p>
        <p>
          <b>7. Retention of your Personal Data</b>
        </p>
        <p>
          The Company will retain your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies.
        </p>
        <p>
          The Company will also retain Usage Data for internal analysis
          purposes. Usage Data is generally retained for a shorter period of
          time, except when this data is used to strengthen the security or to
          improve the functionality of Our Service, or We are legally obligated
          to retain this data for longer time periods.
        </p>
        <p>
          <b>8.Transfer of your Personal Data</b>
        </p>
        <p>
          Your information, including Personal Data, is processed at the
          Company&#39;s operating offices and in any other places where the
          parties involved in the processing are located. It means that this
          information may be transferred to — and maintained on — computers
          located outside of your state, province, country or other governmental
          jurisdiction where the data protection laws may differ from those from
          your jurisdiction.
        </p>
        <p>
          Your consent to this Privacy Policy followed by your submission of
          such information represents your agreement to that transfer.
        </p>
        <p>
          The Company will take all steps reasonably necessary to ensure that
          your data is treated securely and in accordance with this Privacy
          Policy and no transfer of your Personal Data will take place to an
          organization or a country unless there are adequate controls in place
          including the security of your data and other personal information.
        </p>
        <p>
          <b>Disclosure of your Personal Data</b>
        </p>
        <p>
          <b>Business Transactions</b>
        </p>
        <p>
          If the Company is involved in a merger, acquisition or asset sale,
          your Personal Data may be transferred. We will provide notice before
          your Personal Data is transferred and becomes subject to a different
          Privacy Policy.
        </p>
        <p>
          <b>Law enforcement</b>
        </p>
        <p>
          Under certain circumstances, the Company may be required to disclose
          your Personal Data if required to do so by law or in response to valid
          requests by public authorities (e.g. a court or a government agency).
        </p>
        <p>
          <b>Other legal requirements</b>
        </p>

        <p>
          The Company may disclose your Personal Data in the good faith belief
          that such action is necessary to:
        </p>
        <p>1.Comply with a legal obligation</p>
        <p>2.Protect and defend the rights or property of the Company</p>
        <p>
          3. Prevent or investigate possible wrongdoing in connection with the
          Service
        </p>
        <p>
          4.Protect the personal safety of Users of the Service or the public
        </p>
        <p>5.Protect against legal liability</p>
        <p>
          <b>9. Security of your Personal Data</b>
        </p>
        <p>
          The security of your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect your Personal Data, we cannot guarantee
          its absolute security.
        </p>
        <p>
          <b>
            10. Detailed Information on the Processing of your Personal Data
          </b>
        </p>
        <p>
          The Service Providers We use may have access to your Personal Data.
          These third- party vendors collect, store, use, process and transfer
          information about your activity on Our Service in accordance with
          their Privacy Policies.
        </p>
        <p>
          <b>11.Analytics</b>
        </p>
        <p>
          We may use third-party Service providers to monitor and analyze the
          use of our Service.
        </p>
        <p>
          <b>12.Email Marketing</b>
        </p>
        <p>
          We may use your Personal Data to contact you with newsletters,
          marketing or promotional materials and other information that may be
          of interest to you. you may opt- out of receiving any, or all, of
          these communications from Us by following the unsubscribe link or
          instructions provided in any email We send or by contacting Us.
        </p>
        <p>
          <b>13.Children&#39;s Privacy</b>
        </p>
        <p>
          Our Service does not address anyone under the age of 18. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 18. If you are a parent or guardian and you are aware
          that your child has provided Us with Personal Data, please contact Us.
          If We become aware that We have collected Personal Data from anyone
          under the age of 18 without verification of parental consent, we take
          steps to remove that information from Our servers.
        </p>

        <p>
          If We need to rely on consent as a legal basis for processing your
          information and your country requires consent from a parent, we may
          require your parent&#39;s consent before We collect and use that
          information.
        </p>
        <p>
          <b>14.Links to Other Websites</b>
        </p>
        <p>
          Our Service may contain links to other websites that are not operated
          by Us. If you click on a third party link, you will be directed to
          that third party&#39;s site. We strongly advise you to review the
          Privacy Policy of every site you visit.
        </p>
        <p>
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </p>
        <p>
          <b>15. Changes to this Privacy Policy</b>
        </p>
        <p>
          We may update Our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page.
        </p>
        <p>
          We will let you know via email and/or a prominent notice on Our
          Service, prior to the change becoming effective and update the
          &quot;Last updated&quot; date at the top of this Privacy Policy.
        </p>
        <p>
          you are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
        <p>
          <b>16.Contact Us</b>
        </p>
        <p>
          If you have any questions about this Privacy Policy, you can contact
          us:
        </p>

        <p>
          1. By visiting this page on our website:{" "}
          <a
            href="http://saisatishgroups.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <b>http://saisatishgroups.com</b>
          </a>
        </p>
        <p>2. By sending us an email:  saisatishmulti@gmail.com</p>
        <p>
          3. If we make changes to any of our privacy policies or practices
          regarding personal information we will update our statement and post a
          notice on our site 30 days before the changes take effect.
        </p>
      </div>
    </>
  );
}

export default Privacy;
